spring.application.name=freelanceFlow

#Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/freelanceflow_db
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

#App port
server.port=8080

jwt.secret=freelanceflow_super_secret_key_minimum_32_characters_long
jwt.expiration=86400000